apiVersion: v1
kind: Secret
metadata:
  name: signbell-secrets
  namespace: default
type: Opaque
stringData:
  # 민감한 정보는 stringData로 직접 입력 (자동으로 base64 인코딩됨)
  db-password: "mariadb1234"
  jwt-secret: "kq2B8xv4zJ9L1t6Q3w8Y2u5R7o0M3n6B9c2E5h8J1k4="
  kakao-client-id: "b0a11cd4478b43be83addcc4a7ff9516"
  kakao-client-secret: "qP6a7Er2xp1Qy3rT6hToiVZ6VP740mGE"
  api-service-key: "8e94127e-9ea0-4f85-a4af-f36bd7110bb0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: signbell-config
  namespace: default
data:
  SERVER_PORT: "8443"
  DB_URL: "jdbc:mariadb://signbell-db.c9g2mk6gms0l.ap-northeast-2.rds.amazonaws.com:3306/signbell"
  DB_USERNAME: "admin"
  JWT_ACCESS_TOKEN_EXPIRATION: "900000"
  JWT_REFRESH_TOKEN_EXPIRATION: "604800000"
  COOKIE_ACCESS_TOKEN_MAX_AGE: "900"
  COOKIE_REFRESH_TOKEN_MAX_AGE: "604800"
  COOKIE_DOMAIN: ".signbell.app"
  KAKAO_PROD_REDIRECT_URI: "https://api.signbell.app/oauth2/callback/kakao"
  APP_OAUTH2_SUCCESS_REDIRECT_URL: "https://www.signbell.app/terms"
  APP_OAUTH2_FAILURE_REDIRECT_URL: "https://www.signbell.app?from=oauth2"
  API_REQUEST_URL: "https://api.kcisa.kr/openapi/service/rest/meta13/getCTE01701"
